### ISSUE TITLE
What determines the value of DEBUG?

### ISSUE THREAD

**Issue by JHKennedy4** [glimmerjs/glimmer-env#3]
I recently experienced an outage in production caused by DEBUG resolving to true (see: https://github.com/ember-app-scheduler/ember-app-scheduler/issues/69). I'd like to get a better idea of how this value is getting set so we can fix our build appropriately.

Thanks in advance.

**Comment by blimmer** [comment]
Did you figure this out? I'm trying to figure this out, too.
